import { auth, db } from "../../Firebase/firebase-config.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, getDocs } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const productsBody = document.getElementById("productsBody");
const productSearch = document.getElementById("productSearch");
const categoryFilter = document.getElementById("categoryFilter");
const stockFilter = document.getElementById("stockFilter");
const typeFilter = document.getElementById("typeFilter");
const resetFilters = document.getElementById("resetFilters");
const refreshProducts = document.getElementById("refreshProducts");
const totalProducts = document.getElementById("totalProducts");
const availableProducts = document.getElementById("availableProducts");
const lowStockProducts = document.getElementById("lowStockProducts");
const outOfStockProducts = document.getElementById("outOfStockProducts");
const resultCount = document.getElementById("resultCount");
const previousPage = document.getElementById("previousPage");
const nextPage = document.getElementById("nextPage");
const pageNumber = document.getElementById("pageNumber");
const productsError = document.getElementById("productsError");
const productsErrorMessage = document.getElementById("productsErrorMessage");
const retryButton = document.getElementById("retryButton");
const staffName = document.getElementById("staffName");
const staffAvatar = document.getElementById("staffAvatar");
const productModal = document.getElementById("productModal");
const closeModal = document.getElementById("closeModal");
const modalProductId = document.getElementById("modalProductId");
const modalProductName = document.getElementById("modalProductName");
const modalProductSku = document.getElementById("modalProductSku");
const modalCategory = document.getElementById("modalCategory");
const modalPrice = document.getElementById("modalPrice");
const modalStock = document.getElementById("modalStock");
const modalThreshold = document.getElementById("modalThreshold");
const modalStatus = document.getElementById("modalStatus");
const modalStatusBox = document.getElementById("modalStatusBox");
let currentUser = null;
let products = [];
let categories = [];
let filteredProducts = [];
let currentPage = 1;
const pageSize = 10;
const money = value => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(Number(value) || 0);
const initials = name => { const parts = String(name || "Staff").trim().split(/\s+/); return parts.length > 1 ? (parts[0][0] + parts[parts.length - 1][0]).toUpperCase() : String(name || "ST").substring(0, 2).toUpperCase() };
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
const text = value => String(value ?? "").trim();
const getName = item => text(item.name ?? item.productName ?? item.packageName ?? item.insuranceName ?? item.title ?? "Unnamed Item");
const getSku = item => text(item.sku ?? item.SKU ?? item.productCode ?? item.packageCode ?? item.insuranceCode ?? "—");
const getPrice = item => Number(item.sellingPrice ?? item.price ?? item.salePrice ?? item.unitPrice ?? 0);
const getCategory = item => text(item.categoryName ?? item.category ?? item.categoryId ?? "Uncategorized");
const getThreshold = item => Number(item.lowStock ?? item.lowStockAlert ?? item.lowStockThreshold ?? item.reorderLevel ?? 10);
const getRawStock = item => Number(item.stock ?? item.currentStock ?? item.quantity ?? item.availableStock ?? 0);
const getProductStockById = id => { const found = products.find(item => item.itemType === "Product" && String(item.sourceId) === String(id)); return found ? getRawStock(found) : 0 };
const getPackageStock = pkg => { if (Number.isFinite(Number(pkg.stock)) && Object.prototype.hasOwnProperty.call(pkg, "stock")) return Math.max(0, Number(pkg.stock) || 0); const items = Array.isArray(pkg.items) ? pkg.items : Array.isArray(pkg.contents) ? pkg.contents : Array.isArray(pkg.products) ? pkg.products : []; if (!items.length) return 0; const capacities = items.map(item => { const id = item.productId ?? item.id ?? item.product?.id; const qty = Math.max(1, Number(item.quantity ?? item.qty ?? item.requiredQuantity ?? 1) || 1); const stock = getProductStockById(id); return Math.floor(Math.max(0, stock) / qty) }); return capacities.length ? Math.max(0, Math.min(...capacities)) : 0 };
const getStock = item => item.itemType === "Package" ? getPackageStock(item) : getRawStock(item);
const getStatus = item => { const stock = getStock(item); const threshold = getThreshold(item); if (stock <= 0) return "out"; if (stock <= threshold) return "low"; return "available" };
const showError = error => { console.error("Products error:", error); productsError?.classList.add("show"); if (productsErrorMessage) productsErrorMessage.textContent = error?.message || "Unable to load products from Firebase." };
const hideError = () => productsError?.classList.remove("show");
const loadStaffInfo = user => { const name = sessionStorage.getItem("userName") || user.displayName || user.email?.split("@")[0] || "Staff"; if (staffName) staffName.textContent = name; if (staffAvatar) staffAvatar.textContent = initials(name) };
const readCollection = async (name, type) => { const snapshot = await getDocs(collection(db, name)); const result = []; snapshot.forEach(document => { const data = document.data(); result.push({ ...data, sourceId: document.id, id: `${type.toLowerCase()}_${document.id}`, itemType: type }) }); return result };
const loadCategories = async () => { try { const snapshot = await getDocs(collection(db, "categories")); categories = []; snapshot.forEach(document => categories.push({ id: document.id, ...document.data() })); categories = categories.filter(category => text(category.status || "active").toLowerCase() !== "inactive"); categories.sort((a, b) => text(a.name ?? a.categoryName ?? a.title ?? a.id).localeCompare(text(b.name ?? b.categoryName ?? b.title ?? b.id))); if (categoryFilter) { categoryFilter.innerHTML = '<option value="all">All Categories</option>'; categories.forEach(category => { const name = text(category.name ?? category.categoryName ?? category.title ?? category.id); const option = document.createElement("option"); option.value = name; option.textContent = name; categoryFilter.appendChild(option) }) } } catch (error) { console.warn("Category loading skipped:", error); if (categoryFilter) categoryFilter.innerHTML = '<option value="all">All Categories</option>' } };
const setupTypeFilter = () => { if (!typeFilter) return; typeFilter.innerHTML = '<option value="all">All Item Types</option><option value="Product">Products</option><option value="Package">Packages</option><option value="Insurance">Insurance</option>'; typeFilter.value = "all" };
const loadProducts = async () => { if (productsBody) productsBody.innerHTML = '<tr><td colspan="7" class="empty-cell">Loading catalog...</td></tr>'; const results = await Promise.allSettled([readCollection("products", "Product"), readCollection("packages", "Package"), readCollection("insurances", "Insurance")]); const loaded = []; const failures = []; results.forEach((result, index) => { if (result.status === "fulfilled") loaded.push(...result.value); else failures.push(index === 0 ? "Products" : index === 1 ? "Packages" : "Insurance") }); products = loaded; products.sort((a, b) => getName(a).localeCompare(getName(b))); updateSummary(); applyFilters(); if (!products.length) throw new Error(failures.length ? `Unable to load ${failures.join(", ")}.` : "No catalog items found."); if (failures.length) console.warn("Some catalog collections could not be loaded:", failures) };
const updateSummary = () => { let available = 0, low = 0, out = 0; products.forEach(item => { const status = getStatus(item); if (status === "available") available++; if (status === "low") low++; if (status === "out") out++ }); if (totalProducts) totalProducts.textContent = products.length; if (availableProducts) availableProducts.textContent = available; if (lowStockProducts) lowStockProducts.textContent = low; if (outOfStockProducts) outOfStockProducts.textContent = out };
const applyFilters = () => { const search = productSearch?.value.trim().toLowerCase() || ""; const category = categoryFilter?.value || "all"; const stock = stockFilter?.value || "all"; const type = typeFilter?.value || "all"; filteredProducts = products.filter(item => { const name = getName(item).toLowerCase(); const sku = getSku(item).toLowerCase(); const itemCategory = getCategory(item); const matchesSearch = !search || name.includes(search) || sku.includes(search); const matchesType = type === "all" || item.itemType === type; const matchesCategory = category === "all" || itemCategory === category; const matchesStock = stock === "all" || getStatus(item) === stock; return matchesSearch && matchesType && matchesCategory && matchesStock }); currentPage = 1; renderTable() };
const renderTable = () => { const totalPages = Math.max(1, Math.ceil(filteredProducts.length / pageSize)); if (currentPage > totalPages) currentPage = totalPages; const start = (currentPage - 1) * pageSize; const rows = filteredProducts.slice(start, start + pageSize); if (pageNumber) pageNumber.textContent = currentPage; if (previousPage) previousPage.disabled = currentPage <= 1; if (nextPage) nextPage.disabled = currentPage >= totalPages; if (resultCount) resultCount.textContent = `Showing ${filteredProducts.length ? start + 1 : 0}-${Math.min(start + pageSize, filteredProducts.length)} of ${filteredProducts.length} item${filteredProducts.length === 1 ? "" : "s"}`; if (!productsBody) return; if (!rows.length) { productsBody.innerHTML = '<tr><td colspan="7" class="empty-cell">No items found.</td></tr>'; return } productsBody.innerHTML = rows.map(item => { const status = getStatus(item); const stock = getStock(item); const statusText = status === "available" ? "Available" : status === "low" ? "Low Stock" : "Out of Stock"; const stockClass = status === "available" ? "stock-good" : status === "low" ? "stock-low" : "stock-out"; const statusClass = status === "available" ? "status-available" : status === "low" ? "status-low" : "status-out"; const typeClass = item.itemType === "Package" ? "item-type-package" : item.itemType === "Insurance" ? "item-type-insurance" : "item-type-product"; const typeText = item.itemType === "Product" ? "Product" : item.itemType; return `<tr><td><div class="item-name"><span class="item-type-dot ${typeClass}"></span><strong>${escapeHtml(getName(item))}</strong></div></td><td>${escapeHtml(getSku(item))}</td><td><span class="type-badge ${typeClass}">${escapeHtml(typeText)}</span>${getCategory(item) !== "Uncategorized" ? `<small class="category-sub">${escapeHtml(getCategory(item))}</small>` : ""}</td><td>${money(getPrice(item))}</td><td><span class="stock-number ${stockClass}">${stock}</span></td><td><span class="status-badge ${statusClass}">${statusText}</span></td><td><button class="view-button" data-id="${escapeHtml(item.id)}">View</button></td></tr>` }).join(""); document.querySelectorAll(".view-button").forEach(button => button.addEventListener("click", () => openProduct(button.dataset.id))) };
const openProduct = id => { const item = products.find(entry => entry.id === id); if (!item) return; const status = getStatus(item); const statusText = status === "available" ? "Available" : status === "low" ? "Low Stock" : "Out of Stock"; if (modalProductId) modalProductId.textContent = `${item.itemType} ID: ${item.sourceId}`; if (modalProductName) modalProductName.textContent = getName(item); if (modalProductSku) modalProductSku.textContent = getSku(item); if (modalCategory) modalCategory.textContent = item.itemType === "Package" ? "Package" : item.itemType === "Insurance" ? "Insurance" : getCategory(item); if (modalPrice) modalPrice.textContent = money(getPrice(item)); if (modalStock) modalStock.textContent = getStock(item); if (modalThreshold) modalThreshold.textContent = getThreshold(item); if (modalStatus) modalStatus.textContent = statusText; if (modalStatusBox) { modalStatusBox.style.background = status === "available" ? "#eaf7ef" : status === "low" ? "#fff4df" : "#fdecec"; modalStatusBox.style.color = status === "available" ? "#16803c" : status === "low" ? "#d98200" : "#d74343" } if (productModal) productModal.classList.add("show") };
const refresh = async () => { if (!currentUser) return; try { hideError(); setupTypeFilter(); await loadCategories(); await loadProducts() } catch (error) { showError(error) } };
productSearch?.addEventListener("input", applyFilters);
typeFilter?.addEventListener("change", applyFilters);
categoryFilter?.addEventListener("change", applyFilters);
stockFilter?.addEventListener("change", applyFilters);
resetFilters?.addEventListener("click", () => { if (productSearch) productSearch.value = ""; if (typeFilter) typeFilter.value = "all"; if (categoryFilter) categoryFilter.value = "all"; if (stockFilter) stockFilter.value = "all"; applyFilters() });
refreshProducts?.addEventListener("click", refresh);
retryButton?.addEventListener("click", refresh);
previousPage?.addEventListener("click", () => { if (currentPage > 1) { currentPage--; renderTable() } });
nextPage?.addEventListener("click", () => { const totalPages = Math.max(1, Math.ceil(filteredProducts.length / pageSize)); if (currentPage < totalPages) { currentPage++; renderTable() } });
closeModal?.addEventListener("click", () => productModal?.classList.remove("show"));
productModal?.addEventListener("click", event => { if (event.target === productModal) productModal.classList.remove("show") });
onAuthStateChanged(auth, async user => { if (!user) { window.location.href = "../login.html?role=staff"; return } currentUser = user; loadStaffInfo(user); await refresh() });
